# Generated by Django 4.0 on 2021-12-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=50)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateOfBirth', models.DateTimeField()),
                ('address', models.TextField(max_length=250)),
                ('designation', models.CharField(max_length=15)),
                ('ward', models.CharField(max_length=15)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('payMatrix', models.CharField(max_length=35)),
                ('image', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=30)),
                ('dateOfBirth', models.DateTimeField()),
                ('image', models.FileField(upload_to='media/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
    ]
