# Generated by Django 4.0 on 2021-12-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_employee_dependent_eid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='dateOfBirth',
            field=models.DateField(),
        ),
    ]
