# Generated by Django 4.0 on 2021-12-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dependent_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
