# Generated by Django 4.0 on 2021-12-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dependent_image_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='image',
            field=models.ImageField(default='default.png', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default.png', upload_to='static/images'),
        ),
    ]
